### ISSUE TITLE
Navigation dropdown image

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#1]
When you click on the main nav links a drop down appears with the 2nd level navigation. Each of these has a 'Market and Fund Performance' graph image. Can this image be replaced with the 3 images from the home page (2x2 grid) for the investment, insurance and pension sections?

**Comment by seonzoo** [comment]
Need Peter to provide 4 images that are correct size and without watermarks!

**Comment by stephnyc** [comment]
latest version sent to NI for approval

**Comment by stephnyc** [comment]
replace the image on the customer product drop downs with the relevant phone number(s) from the can we help tab

**Comment by seonzoo** [comment]
Still need exact text for each

**Comment by MartinZOO** [comment]
Per Peter's design, with the following numbers for each section:

Life Insurance
1850 200 318


Investments
1850 200 318


Pensions
(01) 6172798

Customer Service
(01) 6172000

**Comment by seonzoo** [comment]
complete but needs css tweaking for smaller viewports
