### ISSUE TITLE
GF to add Literature and change headings

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#100]
GF: where do I change the headings for the Literature on the new site? also come to think of it, where do I add/delete lit?

**Comment by stephnyc** [comment]
Agreed at meeting to change the edit PDF functionality to be similar to 'PDF Upload'

- show all broker lit.
- show all f.advisor lit.
+ drill downs

no pagination needed if all docs are scrollable
can add new categories as well as new docs

**Comment by seonzoo** [comment]
added ability to edit pdf categories & types. will need to do a bit of testing and rewrite some sql queries for literature library
