### ISSUE TITLE
Admin text format options

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#102]
Change to allow GF to select font sizes 10, 12, 14
Remove 'warning box' option 
Change padding in header-box as per meeting 25/2/15 (not all caps, 4px less padding top/bottom, font size 16)

**Comment by seonzoo** [comment]
fixed header-box css and updated editor dropdown with 12px/ 10px text options.

Will probably need to go through every page again and make sure the new formatting is consistent and correct.
