### ISSUE TITLE
IE8 Literature Centre

### ISSUE THREAD

**Issue by MartinZOO** [zoodigital/nia#105]
George reports: main issues seem to be around the Literature for Brokers, it doesn't always expand down (in the instance below I'm hovered over investments and nothing is happening)  Also, on the literature section of the dashboard you can't change from Protection lit.

**Comment by MartinZOO** [comment]
I wasn't able to reproduce this using IE Tab set to IE8 - everything worked fine.

**Comment by seonzoo** [comment]
this is probably because the fund centre graph is throwing an error - once we find a solution for #107 this should be ok
