### ISSUE TITLE
[future] call us now - different message at diff times

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#11]
requirement - ' call us now ' during opening hours and 'contact us during business hours' after hours

**Comment by seonzoo** [comment]
where exactly?

**Comment by stephnyc** [comment]
on the pop out (or anywhere that shows the opening hours i guess).. not a high priority, but have a think about it

**Comment by seonzoo** [comment]
Think this needs design really.

**Comment by stephnyc** [comment]
he doesnt want the small text (in the box) to say 'call us now'... show times or nothing in this spot

**Comment by stephnyc** [comment]
closed - see #59
