### ISSUE TITLE
BROKER - 'Can we help?' change list of phone numbers

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#21]
'Can we help?' text - how many contact numbers do we have? what contact data is useful for brokers? (ZOO to identify the impact)
- waiting on NIA

**Comment by stephnyc** [comment]
Sales support (01) 6176524 sales.support@newireland.ie 
Broker Underwriting (01) 5119298 underwriting@newireland.ie
Life & Pensions Technical (01) 6172328 lifeandpensions@newireland.ie 
Broker New Business Dublin (01) 6322000 brokernewbusiness@newireland.ie 
Broker New Business Country (01) 6322322 brokernb@newireland.ie

Martin asked Peter for a design

**Comment by seonzoo** [comment]
Complete but needs css tweaks for smaller viewport
