### ISSUE TITLE
Customer Service Menu Content

### ISSUE THREAD

**Issue by MartinZOO** [zoodigital/nia#44]
As discussed earlier, clicking on customer service should expand showing 4 sub-navs:
Contact Us (List to be amended)
About Us (as is for now)
Popular Customer Forms (with you, 3 forms to follow)
Careers (as is for now)
 
The reception number (01) 6172000 should show in opposite the sub-navs instead of the placeholder image to keep it consistent with the rest of the customer site navigation.

**Comment by seonzoo** [comment]
Don't recall this was discussed. Will need a half-height phone number graphic if there are only 2x2 subnav items

**Comment by seonzoo** [comment]
DUPLICATE OF #32
