### ISSUE TITLE
Broker: Lit. Centre panel - unclick star - unexpected action

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#48]
When I open the broker dashboard and view the Literature centre panel, I already have some favourites chosen (they appear as expected with stars)

When I click a star, I expected to unselect a favourite. However all the favourite stars unclick (not just the one I click) - clicking re-enables ALL stars as well.

Also when I click & unclick a few times, I get the message "not so fast" - though I'm guessing thats intentional?

**Comment by seonzoo** [comment]
Yes, this is a bug there is a php error in the console

**Comment by seonzoo** [comment]
Should be fixed, json_decode was returning null instead of an empty array when there was a cookie but no favdocs recorded

**Comment by stephnyc** [comment]
this may be working, but my favourites are not appearing in the panel. If I go to the full Lit Center then they still retained their star.

**Comment by seonzoo** [comment]
no

**Comment by stephnyc** [comment]
what does that mean?

**Comment by seonzoo** [comment]
no I'm not seeing it you must be overlooking something or this is the same as issue #57 - where the back button is not retaining the ajax loaded data.

**Comment by stephnyc** [comment]
so, now the original issue is back

when you unclick a favourite (on the panel) all of them unclick

**Comment by seonzoo** [comment]
the user is not supposed to be able to remove favs from the dashboard

**Comment by stephnyc** [comment]
Yes they are - it was functionality requested by NIA

Stephanie McDonnell | Project Manager | *ZOO* Digital | 01 5250957 | 087
2242413 | stephanie@zoodigital.ie

**Comment by seonzoo** [comment]
well this introduces a whole load of extra work to remove the li items and dynamically update the default list by calling an extra query to fins the sticky docs again. this is alos going to require the same fix for issue57 - ive no idea how long this is going to take so im going to advise that we leave it out for go live
