### ISSUE TITLE
Find an advisor - Showing All (doesnt change for filters)

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#51]
I thought we were removing this title - but if not, shouldnt it also say "Showing Results" when a county or if filtered & showing only brokers for example

Could also say "Showing Dublin" ; "Showing Brokers" .. but "Showing Results" would at least let you know if was filtered and provide the [x] to remove filter

**Comment by stephnyc** [comment]
Actually - entered 'finance' in Search box and got 'Showing Results' [x] 
but clicking [x] did not remove the filter (and show all) - what is the [x] supposed to do?

**Comment by seonzoo** [comment]
it is supposed to reset the map but was not behaving since we added the broker/advisor filter. fixed now

**Comment by stephnyc** [comment]
I'm looking on Chrome - it is now saying "Showing    [x]" but does not say the county or Broker/Advisor - should it?
