### ISSUE TITLE
Investments Content - add 'awards'

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#53]
http://**.*/investments/our_fund_managers.aspx

Add 'Awards' content to each Fund Manager

**Comment by seonzoo** [comment]
new designs - are these for go live?

**Comment by stephnyc** [comment]
You'd have to ask Martin.

this page needs more work... GF wants expand/collapse, images instead of bullets, logos on white background.. get email he sent with screenshot 11/02/15
