### ISSUE TITLE
literature center : mobile/ipad

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#67]
when full lit.center opens 2 section categories can be seen with the 3rd moved to next line (on mobile each of the 3 section categories are vertical) 

also on mobile the pdf names only show approx 15 chars which is not enough to distinquish docs 

assume Pete is looking at a design?

**Comment by seonzoo** [comment]
there was never a mobile strategy for the broker section

**Comment by stephnyc** [comment]
Sprint #2 as it needs design first
