### ISSUE TITLE
iFUNDs - change the banner

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#69]
replace the current "rubik cube" image on this page  http://*****/investments/ifunds/  

with the attached animated gif 

\Website\Design\Assets\iFunds_Banner_686-x-265.gif

**Comment by seonzoo** [comment]
this is public please dont use real urls or clients names

**Comment by stephnyc** [comment]
totally agree - how about you delete it when you make the change? 

or do you want separate emails or messages?

**Comment by seonzoo** [comment]
theres no need - just use the later part of the url - the closed items still show up on github
