### ISSUE TITLE
H3 very large on landing page

### ISSUE THREAD

**Issue by MartinZOO** [zoodigital/nia#70]
***.**/insurance/about-insurance/
Is the AllCaps H3 supposed to be that large?

**Comment by seonzoo** [comment]
show me - looks fine / consistent with rest of the site here

**Comment by stephnyc** [comment]
GF still doesnt like it. He says the font and whitespace take up too much room and that it will be used to take a quote from an article for example. Need a designer?

**Comment by seonzoo** [comment]
missed the h3 tag in question - it was certainly too big. fixed it so should now be consistent with other h3 tags.
