### ISSUE TITLE
Submenu Titles - Life Insurance

### ISSUE THREAD

**Issue by MartinZOO** [zoodigital/nia#71]
George said that 'Life Cover' should change to 'Life Insurance' but that would give us 'About Life Insurance' and 'Life Insurance'  The first submenu item is really 'About Insurance' - we need to verify this is ok with George.

**Comment by stephnyc** [comment]
Change Insurance headings
- About life insurance => Why insurance
- Life Cover => Life Insurance

**Comment by stephnyc** [comment]
GF has tried to modify these, with interesting results. 

Can you take a look? thanks
