### ISSUE TITLE
Cookies Page

### ISSUE THREAD

**Issue by MartinZOO** [zoodigital/nia#74]
We don't actually use targeting cookies but should probably leave the text as is.  It might need table borders so that the Cookie Type and Description are easier to associate.
**/utilities/cookies/

**Comment by stephnyc** [comment]
GF email 17/2/15 "Cookies text is to be the exact same as BOI please This site places cookies on your device. By using this site, you agree that we may store and access cookies on your device. To find out how we use cookies and also how you can change your cookie settings, click here."

**Comment by seonzoo** [comment]
should have been closed. already done.
