### ISSUE TITLE
Fund Centre on Broker Dashboard

### ISSUE THREAD

**Issue by MartinZOO** [zoodigital/nia#76]
Funds shown should be iFunds.

**Comment by seonzoo** [comment]
its showing fav funds for demo if thats what you mean?

**Comment by stephnyc** [comment]
it was requested that the default funds (assuming no faves selected) would be iFUNDS3, 4, 5 & iFUND Equities

**Comment by seonzoo** [comment]
yes that is how it is behaving - ive removed the cookie emulation which was just in place to get the fav stars css showing up
