### ISSUE TITLE
Investment content update - need design

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#8]
Investment changes - upload new text to site (see email 29/1/15)

**Comment by seonzoo** [comment]
dont have email

**Comment by seonzoo** [comment]
I've added content but still there are two pages outstanding that need design - Market watch & Our Fund Managers

**Comment by seonzoo** [comment]
Content updates have been made according to 'Review 03.02.15.doc'
Can Peter have a look over these?
- Market watch page needs most attention - examples in doc

**Comment by stephnyc** [comment]
No action to be taken on Market Watch until after launch - MB

**Comment by stephnyc** [comment]
Redesigned layout needed for launch
