### ISSUE TITLE
2nd level does not match 1st level drop down

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#83]
I had thought we were going to make it so the nav only had to be changed in one place? but even if not, they need to be the same for launch

This is most noticeable on Customer Service

1st level drop down =
CONTACT US
ABOUT US
CAREERS
POPULAR CUSTOMER FORMS

2nd level nav (on right) =
Contact
Privacy Statement
Terms & Conditions
Sitemap
Careers
Group Pension Login
Useful Links
Cookies

**Comment by seonzoo** [comment]
no i dont remember agreeing to that

**Comment by stephnyc** [comment]
well even if you are not going to automate it, can you make sure both navs have the same links? thanks

**Comment by seonzoo** [comment]
sure we can do this but I'm betting someone will ask to change it back when it doesn't look good
