### ISSUE TITLE
CTA button needed - for example iFUNDS page

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#87]
GF would like  a standard button to be created to use throughout the site "Read More" or "Find out more".... these would usually link to a PDF (but he doesnt want the same PDF icon as Lit Library)

**Comment by stephnyc** [comment]
GF wouild like 2 buttons
1 - low level link to PDF
2 - promoted link (more exciting)

**Comment by stephnyc** [comment]
this is the requirement to have "Learn More" button be editable - Seón if this is already possible, can you close this?

**Comment by seonzoo** [comment]
yes - the extra field ( LINK TEXT ) is editable for footer items
