### ISSUE TITLE
how do I....? change the FAQ

### ISSUE THREAD

**Issue by stephnyc** [zoodigital/nia#99]
GF 19/2/15 "where do I change the items that appear under the FAQ dropdown for pensions etc?"

**Comment by seonzoo** [comment]
There is an expected fix in wordpress 4.2 to allow control of menu items for 'editors' but for now this will have to be restricted to administrators

**Comment by stephnyc** [comment]
upgrade GF to admin

**Comment by seonzoo** [comment]
GF is now admin.
